services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysqlJava
    environment:
      MYSQL_USER: "demo_java"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_PASSWORD: "java"
      MYSQL_DATABASE: "data_jpa"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/denrax/Projects/data/mysqldata:/var/lib/mysql

volumes:
  mysqlJPA: