services:
  postgres:
    image: postgres:latest
    container_name: postgresJava
    environment:
      POSTGRES_PASSWORD: "password123"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "jpa"
    ports:
      - '5432:5432'
    volumes:
      - /home/denrax/Projects/data/pgdata:/var/lib/postgresql/data

volumes:
  postgresJPA: