services:
  postgres:
    image: mysql/mysql-server:5.7
    container_name: mysqlJava
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_DB: "data_jpa"
    ports:
      - '3306:3306'
    volumes:
      - /home/denrax/Projects/data/mysqldata:/var/lib/mysqldata/data

volumes:
  mysqlJPA: