spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true