services:
  postgres:
    image: postgres:latest
    container_name: postgresJava
    environment:
      POSTGRES_PASSWORD: "password123"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "jpa"
    ports:
      - '5432:5432'
    volumes:
      - postgresJPA:/var/lib/postgresql/dataJpa

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - '80:80'
    depends_on:
      - postgres

volumes:
  postgresJPA:
